[servers]
worker-node-1 ansible_host=3.142.246.200 ansible_user=ubuntu
worker-node-2 ansible_host=18.217.177.23 ansible_user=ubuntu

[all:vars]
ansible_ssh_private_key_file=/home/ubuntu/ansible-master-key
ansible_python_interpreter=/usr/bin/python3

